name: Deploy FastAPI via AWS SSM

on:
  workflow_dispatch: # Permite ejecutar manualmente el pipeline

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Configurar credenciales de AWS
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # 2. Instalar clave SSH
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: unnecessary

      # 3. Agregar el host a known_hosts
      - name: Adding Known Hosts
        run: |
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Debugging Secrets
        run: |
            echo "SSH_PORT: ${{ secrets.SSH_PORT }}"
            echo "SSH_USER: ${{ secrets.SSH_USER }}"
            echo "SSH_HOST: ${{ secrets.SSH_HOST }}"

      - name: Debug Workspace
        run: |
           echo "Checking workspace..."
           ls -l
           ls
           pwd
           

      # 4. Sincronizar archivos con rsync
      - name: Deploy with rsync
        run: |
            rsync -avz -e "ssh -p ${{ secrets.SSH_PORT }}" . ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/home/${{ secrets.SSH_USER }}/my-app/

      - name: Debug Workspace
        run: |
           echo "Checking workspace..."
           ls
           pwd

      # 5. Reiniciar el servidor
      - name: Restart Server and Deploy Code
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
              git clone https://github.com/tatimun/PythonCompile.git PythonCompile/
              cd PythonCompile/ && git pull
