name: Deploy FastAPI via AWS SSM

on:
  workflow_dispatch: # Permite ejecutar manualmente el pipeline

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Configurar credenciales de AWS
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # 2. Ejecutar comandos en la instancia EC2 con SSM
      - name: Deploy Docker Compose via SSM
        run: |
          aws ssm send-command \
            --targets "Key=tag:Name,Values=FastAPIStack" \
            --document-name "AWS-RunShellScript" \
            --comment "Deploying application via Docker Compose" \
            --parameters '{"commands":[
              "cd /home/ec2-user",
              "rm -f docker-compose.yml",
              "cat <<EOF > docker-compose.yml",
              "version: \\\"3.8\\\"",
              "services:",
              "  pythoncompile:",
              "    image: 140023394742.dkr.ecr.us-east-1.amazonaws.com/fastapi-app:latest",
              "    container_name: pythoncompile-app",
              "    ports:",
              "      - \\\"8000:8000\\\"",
              "    environment:",
              "      - OPENAI_API_KEY=${OPENAI_API_KEY}",
              "EOF",
              "aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 140023394742.dkr.ecr.us-east-1.amazonaws.com",
              "docker-compose pull",
              "docker-compose up -d"
            ]}' \
            --region us-east-1
