name: Deploy FastAPI via AWS SSM

on:
  workflow_dispatch: # Permite ejecutar manualmente el pipeline

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Configurar credenciales de AWS
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # 2. Ejecutar comandos en la instancia EC2 con SSM
      - name: Deploy Docker Compose on EC2
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          USER: ssm-user
          HOST: 98.82.165.50
        run: |
          echo "$SSH_PRIVATE_KEY" > key.pem
          chmod 600 key.pem
          ssh -o StrictHostKeyChecking=no -i key.pem $USER@$HOST << 'EOF'
            # Instalar Git si no está instalado
            if ! command -v git &> /dev/null; then
              sudo yum install -y git || sudo apt-get install -y git
            fi

            # Clonar el repositorio en la instancia EC2
            if [ ! -d "pythoncompile" ]; then
              git clone https://github.com/tatimun/PythonCompile.git pythoncompile
            else
              cd pythoncompile && git pull
            fi

            # Autenticarse con ECR
            aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 438465160540.dkr.ecr.us-east-1.amazonaws.com/fastapi-app

            # Cambiar al directorio y desplegar con Docker Compose
            cd pythoncompile/
            docker-compose up -d
          EOF
