name: Deploy FastAPI via Docker Compose

on:
  workflow_dispatch: # Permite ejecutar manualmente el pipeline

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Configurar las credenciales de AWS
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # 2. Clonar y ejecutar docker-compose en EC2 vía SSM
      - name: Deploy Docker Compose via SSM
        run: |
          aws ssm send-command \
            --targets "Key=tag:Name,Values=FastAPIStack" \
            --document-name "AWS-RunShellScript" \
            --comment "Cloning repo and deploying Docker Compose" \
            --parameters '{"commands":[
              "cd /home/ec2-user",
              "rm -rf fastapi-repo",
              "git clone https://github.com/tatimun/PythonCompile.git fastapi-repo",
              "cd fastapi-repo",
              "aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin 140023394742.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com",
              "ls"
            ]}' \
            --region ${{ secrets.AWS_REGION }}
